version: "3.9"

services:
  frontend:
    build: ./next-app
    container_name: next-frontend
    ports:
      - "3000:3000"
    command: npm run dev
    stdin_open: true
    tty: true
    depends_on:
      - backend

  backend:
    build: ./Flask-app
    container_name: flask-backend
    ports:
      - "5000:5000"
    volumes:
      - ./Flask-app:/app
    command: python main.py
    stdin_open: true
    tty: true
    depends_on:
      - mongo-db

  mongo-db:
    image: mongo:8
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
